name: Append Today Dart Log

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  append-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기

      - name: Set current date
        run: echo "NOW=$(date '+%Y-%m-%d %H:%M %Z')" >> $GITHUB_ENV

      - name: Pull latest to avoid conflicts
        run: |
          git config --global user.name "onbit-bot"
          git config --global user.email "onbit-bot@users.noreply.github.com"
          git pull --rebase origin ${GITHUB_REF_NAME} || true

      - name: Generate Dart change log
        run: |
          LOG_FILE="docs/append_dart_log.md"
          mkdir -p docs
          echo "# 📝 Dart Change Log" > $LOG_FILE
          echo "Generated at: $NOW" >> $LOG_FILE
          echo -e "\n## 🔄 Recent Dart File Changes\n" >> $LOG_FILE

          # 최근 24시간 내 .dart 파일 변경 찾기
          FILES=$(git log --since="24 hours ago" --name-only --pretty=format: | grep '\.dart$' | sort | uniq)
          echo "Detected files: $FILES"
          if [ -z "$FILES" ]; then
            echo "No Dart file changes detected in the last 24 hours." >> $LOG_FILE
          else
            echo "$FILES" | sed 's/^/- /' >> $LOG_FILE
          fi

      - name: Debug log file and Git status
        run: |
          echo "Content of append_dart_log.md:"
          cat docs/append_dart_log.md
          echo "Git status:"
          git status

      - name: Commit and push updated log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add docs/append_dart_log.md
          git commit -m "docs: update Dart change log @ $NOW" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/hundeok/onbit_v2_triple.git || echo "⚠️ Push failed"