name: Append Today Dart Log

on:
  workflow_dispatch:

jobs:
  append-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기

      - name: Set current date
        run: echo "NOW=$(date '+%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      - name: Pull latest to avoid conflicts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main || true

      - name: Append modified Dart files to log
        run: |
          LOG_FILE="docs/append_dart_log.md"
          mkdir -p docs
          touch $LOG_FILE
          echo "" >> $LOG_FILE
          echo "## 🕒 $NOW" >> $LOG_FILE
          echo "" >> $LOG_FILE

          LAST_COMMIT=$(git log --since="24 hours ago" -1 --format=%H)
          echo "Last commit: $LAST_COMMIT"
          FILES=$(git diff --name-only --diff-filter=ACM HEAD^ HEAD | grep '\.dart$' | sort)
          echo "Detected files: $FILES"
          if [ -z "$FILES" ]; then
            echo "No Dart file changes detected." >> $LOG_FILE
          else
            echo "$FILES" | sed 's/^/- /' >> $LOG_FILE
          fi

      - name: Debug log file and Git status
        run: |
          echo "Content of append_dart_log.md:"
          cat docs/append_dart_log.md
          echo "Git status:"
          git status

      - name: Commit and push updated log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add docs/append_dart_log.md
          git commit -m "docs: update Dart log @ $NOW" || true
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/hundeok/onbit_v2_triple.git || echo "⚠️ Push failed"