name: Append Today Dart Log

on:
  workflow_dispatch:    # 수동 실행을 위한 트리거

jobs:
  append-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set current date
        run: echo "NOW=$(date '+%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      - name: Pull latest to avoid conflicts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase || true

      - name: Append modified Dart files to log
        run: |
          mkdir -p gpt_context
          LOG_FILE="gpt_context/today_log.md"
          echo "" >> $LOG_FILE
          echo "## 🕒 $NOW" >> $LOG_FILE
          echo "" >> $LOG_FILE

          # 파일 목록 추출
          FILES=$(git diff --name-only --diff-filter=ACM $(git log --since=midnight -1 --format=%H) | grep '\.dart$' | sort)

          # 변경된 파일이 없다면 종료
          if [ -z "$FILES" ]; then
            echo "No Dart file changes today."
            exit 0
          fi

          # 수정된 파일을 로그에 추가
          echo "$FILES" | sed 's/^/- /' >> $LOG_FILE

      - name: Commit and push updated log
        run: |
          git add gpt_context/today_log.md
          git commit -m "docs: update Dart log @ $NOW" || echo "⚠️ No changes to commit"
          git push || echo "⚠️ Push failed (possibly no new commit)"
