name: Auto Project Report

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-project-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Generate Project Report
        run: |
          mkdir -p docs
          python .github/workflows/extract_workflow_steps.py > docs/project_report.md

      - name: Commit and Push Project Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/project_report.md
          git commit -m "docs: auto-update project report 🧠"
          git push
